version: '3.8'

services:
  app:
    build:
      context: ./Cinema-booking
      dockerfile: Dockerfile
    container_name: cinema-booking-app
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://cinema-booking-db:5432/cinema_booking
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - postgres
    volumes:
      - ./Cinema-booking/uploads:/app/uploads

  postgres:
    image: postgres:18-alpine
    container_name: cinema-booking-db
    environment:
      POSTGRES_DB: cinema_booking
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
